config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments
  get '/', to: 'application#main'
  root 'application#main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def main
    render 'layouts/main'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.new
  end

  def index
    @post = Post.find_by(id: params[:post_id])
    @comments = @post.comments
  end

  def create
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.create!(comment_params)
    @post.comments << @comment
    respond_to do |format|
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  protect_from_forgery except: [:index]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def create
    @post = Post.create!(post_params)
    respond_to do |format|
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_add.html.erb
<div id="create-comment-<%post.id %>">
  <%= link_to "Create comment", new_post_comment_path(post_id: post.id), remote: true %>
</div>

app/views/comments/_comment.html.erb
  <div class="card mb-3" id="comment-<%=comment.id %>">
    <div class="card-body">
      <div class="card-body">
        <p class="card-text"><%= comment.content%></p>
      </div>
    </div>
  </div>

app/views/comments/_new.html.erb
<%= form_with model: comment, url: post_comments_path do |form| %>
  <p>
    <%= form.text_area :content%>
  </p>

  <div class="row">
    <div class="col-sm-11">
      <p>
        <%= form.submit class: "btn btn-primary"%>
      </p>
    </div>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#create-comment-<%=@post.id %>").html("<%= j render(partial: 'comments/add', locals: {post: @post}) %>");
$("#post-<%=@post.id%>-comments").append("<%= j render(@comment) %>")
$("comment-<%=@comment.id %>").append("<%= j render(@comment) %>")
document.getElementById("comment-<%=@comment.id %>").classList.add("border-primary")
setTimeout(function(){
    document.getElementById("comment-<%=@comment.id %>").classList.remove("border-primary")
}, 5000);

$.ajax({
    success: function(){
        alert( "Comment was created!" );
    }
});

app/views/comments/index.html.erb
<% content_for :title do %>
  Comments
<% end %>

<span>Text in red</span>

app/views/comments/index.js.erb
$("#post-<%=@post.id%>-comments").html("<%= j render(partial: 'comment', collection: @comments) %>");

app/views/comments/new.js.erb
$("#create-comment-<%=@post.id %>").html("<%= j render(partial: 'comments/new', locals: {comment: @comment}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<% content_for :title do %>
  Main
<% end %>

<%= link_to "Page 1", posts_path%>
<%= link_to "Page 2", comments_path %>

app/views/posts/_form.html.erb
<div id="target-for-change">
  <%= button_to 'Create post', new_post_path, method: :get, class: "btn btn-primary", remote: true %>
</div>

app/views/posts/_new.html.erb
<%= form_with model: post, url: posts_path, remote: true do |form| %>
  <p>
    <%= form.text_area :title%>
  </p>

  <p>
    <%= form.text_area :content%>
  </p>

  <div class="row">
    <div class="col-sm-11">
      <p>
        <%= form.submit class: "btn btn-primary"%>
      </p>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="target-for-change">
  <div class="card mb-3">
    <div class="card-body">
       <div class="card-body">
         <p class="card-text"><%= post.title%></p>
         <p class="card-text"><%= post.content%></p>
        </div>
    </div>
    <div id="post-<%=post.id%>-comments">
      <%= link_to "Show comments", post_comments_path(post_id: post.id), remote: true %>
    </div>
    <div id="create-comment-<%=post.id %>">
      <%= link_to "Create comment", new_post_comment_path(post_id: post.id), remote: true %>
    </div>
  </div>
</div>

app/views/posts/_show.html.erb
Now you don't!

app/views/posts/create.js.erb
$("#posts").append("<%= j render(@post) %>")
$("#target-for-change").html("<%= j render(partial: "form") %>");

app/views/posts/index.html.erb
<% content_for :title do %>
  Posts
<% end %>

<div class="custom">
</div>
<span>Plain text</span>

app/views/posts/new.js.erb
$("#target-for-change").html("<%= j render(partial: 'new', locals: {post: @post}) %>");

app/views/posts/show.js.erb
$("#target").html("<%= j render(partial: 'show') %>");